# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI - Testes

#quando executar
on:
  push:
    branches: [ main ]
    
    #cron schedule - definir horarios 
    
    workflow_dispatch:

jobs:
  build:
#qual versao
    runs-on: ubuntu-latest

    steps:
    #baixar codigo
    - uses: actions/checkout@v2
    #configurar node
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
#instalar dependencias         
    - run: npm install
#rodar os testes    
    - run: npx cypress run
#fazer merge do relatorio    
    - run: npm run report:merge
#gerar o relatorio 
    - run: npm run report:generate
#upload artefato
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
       path:mochawesome-report


